DefaultContentLanguage: pt-br
baseURL: https://programai.com/

ignoreFiles:
  - "\\.scss$"
  - "\\.scssc$"

Languages:
  en:
    title: ProgramAi! - Tips, courses and development tutorials.

  pt-br:
    title: ProgramAi! - Dicas, cursos e tutoriais de programação.
    months:
      1: Janeiro
      2: Fevereiro
      3: Março
      4: Abril
      5: Maio
      6: Junho
      7: Julho
      8: Agosto
      9: Setembro
      10: Outubro
      11: Novembro
      12: Dezembro

menu:
  main:
    - name: "Início"
      URL: "/"
      Weight: 1

    - name: "Web"
      URL: "/web/"
      Weight: 2

    - name: "Mobile"
      URL: "/mobile/"
      Weight: 3

params:
  categories:
    web:
        url: "/web/"
    frontend:
        url: "/web/frontend/"
    mobile:
        url: "/mobile/"
    android:
        url: "/mobile/android/"

  author:
      name: Andrew C. Pacifico
      description: >
          Bacharel em Ciência da Computação pela Universidade Federal do Amazonas, MBA em Gerenciamento de Projetos pela Fundação Getúlio Vargas.<br>
          <br>
          Atualmente trabalha como Desenvolvedor Web Fullstack na <a href="http://neemu.com/" target="_blank">Neemu</a>.<br>
          <br>
          Experiência em desenvolvimento nas liguagens C/C++, Java, C#, desenvolvimento Web, e Android.
      url: http://twitter.com/andrewcpacifico
      image: http://graph.facebook.com/799249256779962/picture?type=large 
      social:
        facebook: http://fb.com/andrewcpacifico          
        twitter: http://twitter.com/andrewcpacifico
        gPlus: http://google.com/+AndrewPacifico
        github: http://github.com/andrewcpacifico
        linkedin: http://br.linkedin.com/in/andrewcpacifico

  description: ProgramAi! Blog com dicas, tutoriais, e cursos sobre programação.

  social:
    facebook: http://facebook.com/programaiblog
    twitter: http://twitter.com/programaiblog
    gPlus: http://google.com/+ProgramaiBlog
    youtube: http://www.youtube.com/c/ProgramaiBlog
