DefaultContentLanguage: pt-br
baseURL: http://programai.com/

ignoreFiles:
  - "\\.scss$"
  - "\\.scssc$"

Languages:
  en:
    title: ProgramAi! - Tips, courses and development tutorials.

  pt-br:
    title: ProgramAi! - Dicas, cursos e tutoriais de programação.
    months:
      1: Janeiro
      2: Fevereiro
      3: Março
      4: Abril
      5: Maio
      6: Junho
      7: Julho
      8: Agosto
      9: Setembro
      10: Outubro
      11: Novembro
      12: Dezembro

menu:
  main:
    - name: "Início"
      URL: "/"
      Weight: 1

    - name: "Web"
      URL: "/categories/web/"
      Weight: 2

    - name: "Mobile"
      URL: "/categories/mobile/"
      Weight: 3

params:
  author:
      name: Andrew C. Pacifico
      url: http://twitter.com/andrewcpacifico

  description: ProgramAi! Blog com dicas, tutoriais, e cursos sobre programação.

  social:
    facebook: http://facebook.com/programai
    twitter: http://twitter.com/programai
    gPlus: http://google.com/+ProgramaiBlog
    youtube: http://www.youtube.com/c/ProgramaiBlog