# Site settings
title: ProgramAi! - Dicas, cursos e tutoriais de programação. 
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "//localhost:8000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

paginate: 10
paginate_path: "/:num/"
permalink: /:categories/:title/

lang: pt-BR

author:
  name: 'Andrew Pacifico'
  url: 'http://google.com/+AndrewPacifico'

# Build settings
markdown: kramdown
exclude: [ 
  node_modules, 
  bower_components, 
  bower.json, 
  package.json,
  README.md,
  Gruntfile.js,
  grunt
]

twitter_url: http://twitter.com/programaiblog
fb_url: http://fb.com/programaiblog
gplus_url: http://google.com/+ProgramaiBlog
youtube_url: http://www.youtube.com/c/ProgramaiBlog

# Main Application Menu
main_menu:
  - title: "Início"
    url: "//programai.com"

  - title: "Web"
    url: "//programai.com/web"

  - title: "Android"
    url: "//programai.com/android"

gems: 
  - jemoji
  - jekyll-paginate
  - jekyll-read-more
